(()=>{
'use strict';
const DEV=document.querySelector('meta[name="sanctuary-dev-build"]')?.content==='true'||['localhost','127.0.0.1','[::1]'].includes(location.hostname);
const KEY=DEV?'bb:sanctuary:first-bloom:v2':'bb:sanctuary:first-bloom:release:v2',LEGACY_KEY='bb:sanctuary:v1',SCHEMA=2;
const ROOT='assets/ui/sanctuary/first-bloom/';
const BRANCH='feature/sanctuary-first-bloom',CHECKPOINT='e90a4e02d5645550a7d0c8d89277c0ade1b1ad7a';
const TREE=['Seedling','New Growth','Young Bonsai','Shaped Bonsai','Mature Bonsai','First Bloom'];
const GARDEN=['Untouched Garden','First Lines','Flowing Garden','Balanced Garden','Harmony Garden','First Bloom Garden'];
const RAKES=['still_water','ripple_ring','flowing_river','spiral_wind'];
const MOTIFS=['none','blazing_spiral','akatsuki_cloud','petal_drift','lotus_bloom_bonus','shuriken_vortex','kunai_wind','shinobi_seal_mandala','shuriken_smoke_cloud'];
const STONES=['centered','riverbank','mountain','moss_cluster','rock_spire','stepping_stones'];
const BLOSSOMS=['pink','blue','orange','red','ice','fire'];
const NAME_LAYOUTS=['straight','arc','seal'];
const SHAPES=['balanced','windswept','ascending'];
const ROOT_BY_STAGE=[1,1,2,2,3,4],CANOPY_BY_STAGE=[0,1,2,3,4,4];
const LABEL={still_water:'Still Water',ripple_ring:'Ripple Ring',flowing_river:'Flowing River',spiral_wind:'Spiral Wind',none:'None',blazing_spiral:'Blazing Spiral',akatsuki_cloud:'Akatsuki Cloud',petal_drift:'Petal Drift',lotus_bloom_bonus:'Lotus Bloom',shuriken_vortex:'Shuriken Vortex',kunai_wind:'Kunai Wind',shinobi_seal_mandala:'Shinobi Seal Mandala',shuriken_smoke_cloud:'Shuriken Smoke Cloud',centered:'Centered',riverbank:'Riverbank',mountain:'Mountain',moss_cluster:'Moss Cluster',rock_spire:'Rock Spire',stepping_stones:'Stepping Stones',balanced:'Balanced',windswept:'Wind Swept',ascending:'Ascending',straight:'Straight',arc:'Arc',seal:'Seal',pink:'Pink',blue:'Blue',orange:'Orange',red:'Red',ice:'Ice / Light Blue',fire:'Fire'};
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const cycle=(list,current,delta=1)=>list[(Math.max(0,list.indexOf(current))+delta+list.length)%list.length];
const defaults=()=>({schema:SCHEMA,cycle:'first-bloom',cultivationNumber:1,resources:DEV?{leafEssence:9999,gardenStone:9999,spiritWater:999,harmonySeals:10}:{leafEssence:0,gardenStone:0,spiritWater:0,harmonySeals:0},treeStage:1,treeGrowth:0,rootState:1,canopyType:'green',canopyStage:0,blossomState:0,blossomVariant:'pink',gardenHarmony:0,rakePattern:'still_water',motif:'none',stoneLayout:'centered',nameLayout:'straight',treeShape:'balanced',mossAccent:false,petalAccent:false,treeFx:false,completionClaimed:false,completed:false,grove:[],summonResults:[],lastSummon:null});
function playerName(){try{const p=JSON.parse(localStorage.getItem('bb_player_profile_v1')||'{}');return String(p.username||'PLAYER').trim().slice(0,16)||'PLAYER'}catch{return 'PLAYER'}}
function normalize(raw={}){const d=defaults(),s={...d,...raw,resources:{...d.resources,...raw.resources}};s.schema=SCHEMA;s.cultivationNumber=Math.max(1,Math.floor(Number(s.cultivationNumber)||1));s.treeStage=clamp(Math.round(s.treeStage),1,6);s.treeGrowth=clamp(s.treeGrowth,0,100);s.rootState=clamp(Math.round(s.rootState),1,4);s.canopyType=['green','jade'].includes(s.canopyType)?s.canopyType:'green';s.canopyStage=clamp(Math.round(s.canopyStage),0,4);s.blossomState=clamp(Math.round(s.blossomState),0,3);s.blossomVariant=BLOSSOMS.includes(s.blossomVariant)?s.blossomVariant:'pink';s.gardenHarmony=clamp(s.gardenHarmony,0,100);s.rakePattern=RAKES.includes(s.rakePattern)?s.rakePattern:RAKES[0];s.motif=MOTIFS.includes(s.motif)?s.motif:'none';s.stoneLayout=STONES.includes(s.stoneLayout)?s.stoneLayout:STONES[0];s.nameLayout=NAME_LAYOUTS.includes(s.nameLayout)?s.nameLayout:NAME_LAYOUTS[0];s.treeShape=SHAPES.includes(s.treeShape)?s.treeShape:SHAPES[0];s.grove=Array.isArray(s.grove)?s.grove:[];s.summonResults=Array.isArray(s.summonResults)?s.summonResults:[];for(const k of Object.keys(d.resources))s.resources[k]=Math.max(0,Math.floor(Number(s.resources[k])||0));return s}
function migrateLegacy(){try{const x=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(!x)return null;return normalize({resources:{leafEssence:x.leafEssence,gardenStone:x.gardenStone,spiritWater:x.spiritWater,harmonySeals:x.harmonySeals},treeStage:clamp((x.treeStage||0)+1,1,6),treeGrowth:clamp((((x.treeStage||0)+(x.treeProgress||0)/100)/5)*100,0,100),gardenHarmony:clamp((((x.gardenStage||0)+(x.gardenProgress||0)/100)/5)*100,0,100),treeShape:x.treeShape||'balanced',rakePattern:x.sandPattern==='ripple'?'ripple_ring':x.sandPattern,stoneLayout:x.stoneLayout,grove:(x.completed||[]).map((g,i)=>({...g,id:`legacy-${i+1}`,cultivationNumber:i+1,canopyType:'green',blossomVariant:'pink',motif:'none',nameLayout:'straight'}))})}catch{return null}}
let saveState='loaded',tab='cultivate',toastTimer=null,ceremonyTimer=null;
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'null')||(DEV?migrateLegacy():null)||defaults())}catch{return defaults()}}
let S=load();
function markDirty(){saveState='dirty'}
function save(message){localStorage.setItem(KEY,JSON.stringify(S));saveState='saved';renderStatus();if(message)toast(message);return true}
function reload(){S=load();saveState='loaded';render();toast('Sanctuary save reloaded.')}
function toast(message){const el=$('toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},2100)}
function stageForGrowth(g){return g>=100?6:Math.min(5,Math.floor(g/20)+1)}
function gardenStage(){return S.gardenHarmony>=100?6:Math.min(5,Math.floor(S.gardenHarmony/20)+1)}
function syncDerived(){S.treeGrowth=clamp(S.treeGrowth,0,100);S.treeStage=stageForGrowth(S.treeGrowth);S.rootState=ROOT_BY_STAGE[S.treeStage-1];if(S.canopyStage<CANOPY_BY_STAGE[S.treeStage-1])S.canopyStage=CANOPY_BY_STAGE[S.treeStage-1];if(S.treeGrowth>=85&&S.blossomState<1)S.blossomState=1;if(S.treeGrowth>=92&&S.blossomState<2)S.blossomState=2;if(S.treeGrowth>=100&&S.blossomState<3)S.blossomState=3}
function asset(el,path,show=true){if(!el)return;el.hidden=!show;if(!show){el.removeAttribute('src');return}const src=ROOT+path;if(el.getAttribute('src')!==src)el.src=src}
function stonePath(){return ['centered','riverbank','mountain'].includes(S.stoneLayout)?`sand/stones/layouts/${S.stoneLayout}.png`:`sand/stones/variants/${S.stoneLayout}.png`}
function renderScene(){
 $('cultivationNumber').textContent=S.cultivationNumber;$('leafCount').textContent=S.resources.leafEssence.toLocaleString();$('stoneCount').textContent=S.resources.gardenStone.toLocaleString();$('waterCount').textContent=S.resources.spiritWater.toLocaleString();$('sealCount').textContent=S.resources.harmonySeals.toLocaleString();
 asset($('rootLayer'),`bonsai/roots/rootbase_0${S.rootState}.png`);asset($('trunkLayer'),`bonsai/trunks/trunk_0${S.treeStage}.png`);asset($('canopyLayer'),`bonsai/canopy/${S.canopyType}/canopy_0${Math.max(1,S.canopyStage)}.png`,S.canopyStage>0);asset($('blossomLayer'),`bonsai/blossoms/${S.blossomVariant}/blossom_0${Math.max(1,S.blossomState)}.png`,S.blossomState>0);
 asset($('rakeLayer'),`sand/patterns/${S.rakePattern}.png`,S.gardenHarmony>0);asset($('motifLayer'),S.motif.includes('shuriken')||S.motif.includes('kunai')||S.motif.includes('shinobi')?`sand/motifs/ninja-bonus/${S.motif}.png`:`sand/motifs/${S.motif}.png`,S.motif!=='none');asset($('nameTemplateLayer'),`sand/name-templates/${S.nameLayout}.png`,S.gardenHarmony>=50);asset($('stoneLayer'),stonePath(),S.gardenHarmony>=20);$('mossLayer').hidden=!S.mossAccent;$('petalLayer').hidden=!S.petalAccent;
 const sig=$('gardenSignature');sig.textContent=playerName();sig.dataset.layout=S.nameLayout;sig.hidden=S.gardenHarmony<50;
 for(const [id,file] of [['fxDrift','idle_drift'],['fxRing','wind_ring'],['fxBurst','bloom_burst'],['fxGround','ground_scatter']])asset($(id),`bonsai/fx/${S.blossomVariant}/${file}.png`,S.treeFx);
 $('treeStageLabel').textContent=TREE[S.treeStage-1];$('treePercent').textContent=`${S.treeGrowth}%`;$('treeMeter').style.width=`${S.treeGrowth}%`;$('gardenStageLabel').textContent=GARDEN[gardenStage()-1];$('gardenPercent').textContent=`${S.gardenHarmony}%`;$('gardenMeter').style.width=`${S.gardenHarmony}%`;
 $('gardenScene').dataset.treeShape=S.treeShape;$('gardenScene').dataset.completed=String(S.completed);
}
function choiceGroup(title,key,values,note=''){return `<h3>${esc(title)}</h3><div class="choices">${values.map(v=>`<button class="choice ${S[key]===v?'selected':''}" type="button" data-choice="${key}" data-value="${v}"><strong>${esc(LABEL[v]||v)}</strong>${note?`<small>${esc(note)}</small>`:''}</button>`).join('')}</div>`}
function alreadyRecorded(){return S.grove.some(g=>g.id===`first-bloom-${S.cultivationNumber}`)}
function ready(){return S.treeGrowth===100&&S.gardenHarmony===100&&!S.completionClaimed&&!alreadyRecorded()}
function cultivatePanel(){return `<h2>${esc(TREE[S.treeStage-1])}</h2><p>Water, nourish, and shape the bonsai. Every action spends Sanctuary resources, advances growth, updates the production layers, and saves.</p><div class="actions"><button class="action primary" data-action="water" ${S.treeGrowth>=100?'disabled':''}>WATER · 1 SPIRIT WATER</button><button class="action" data-action="nourish" ${S.treeGrowth>=100?'disabled':''}>NOURISH · 25 LEAF ESSENCE</button><button class="action" data-action="prune" ${S.treeGrowth>=100?'disabled':''}>PRUNE / SHAPE · 15 LEAF + 5 STONE</button>${ready()?'<button class="action primary" data-action="complete">COMPLETE FIRST BLOOM</button>':''}${S.completed?'<button class="action primary" data-action="new-cycle">BEGIN NEW CULTIVATION</button>':''}</div>${choiceGroup('Tree shaping','treeShape',SHAPES,'Balanced art renders in V1; other forms are saved metadata.')}`}
function gardenPanel(){return `<h2>Karesansui Garden</h2><p>Develop Garden Harmony independently using the real sand, motif, name-template, accent, and stone layers.</p><div class="actions"><button class="action primary" data-action="rake" ${S.gardenHarmony>=100?'disabled':''}>RAKE · 10 GARDEN STONE</button><button class="action" data-action="stones" ${S.gardenHarmony>=100?'disabled':''}>PLACE STONES · 20 GARDEN STONE</button><button class="action" data-action="refine" ${S.gardenHarmony>=100?'disabled':''}>REFINE GARDEN · 1 WATER + 10 LEAF</button></div>${choiceGroup('Rake pattern','rakePattern',RAKES)}${choiceGroup('Signature motif','motif',MOTIFS)}${choiceGroup('Stone layout','stoneLayout',STONES)}${choiceGroup('Player-name design','nameLayout',NAME_LAYOUTS)}`}
function grovePanel(){const cards=S.grove.length?S.grove.map(g=>`<article class="grove-card" data-grove-id="${esc(g.id)}"><strong>FIRST BLOOM #${String(g.cultivationNumber).padStart(3,'0')}</strong><small>${esc(new Date(g.completedAt).toLocaleString())}<br>${esc(LABEL[g.treeShape]||g.treeShape)} · ${esc(g.canopyType)} canopy · ${esc(LABEL[g.blossomVariant]||g.blossomVariant)} bloom<br>${esc(LABEL[g.rakePattern]||g.rakePattern)} · ${esc(LABEL[g.motif]||g.motif)} · ${esc(LABEL[g.stoneLayout]||g.stoneLayout)} · ${esc(LABEL[g.nameLayout]||g.nameLayout)}</small></article>`).join(''):'<div class="notice">Your Grove is empty. Complete First Bloom to preserve a cultivation here.</div>';return `<h2>The Grove</h2><p>${S.grove.length} completed cultivation${S.grove.length===1?'':'s'} saved on this device.</p><div class="grove-grid">${cards}</div>`}
function summonPanel(){return `<h2>Sanctuary Summon</h2><p>Harmony Seals: <strong>${S.resources.harmonySeals}</strong>. This isolated test summon consumes exactly one Seal and does not touch the normal Summon system.</p><div class="actions"><button class="action primary" data-action="summon" ${S.resources.harmonySeals<1?'disabled':''}>SANCTUARY TEST SUMMON · 1 SEAL</button></div>${S.lastSummon?`<div class="summon-result"><small>TEST REWARD</small><strong>${esc(S.lastSummon.reward)}</strong><span>${esc(new Date(S.lastSummon.at).toLocaleString())}</span></div>`:''}`}
function renderPanel(){const html=tab==='cultivate'?cultivatePanel():tab==='garden'?gardenPanel():tab==='grove'?grovePanel():summonPanel();$('actionPanel').innerHTML=html;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function renderStatus(){if(!$('devStatus'))return;$('devStatus').textContent=`SANCTUARY DEV STATUS\n\nBuild: First Bloom Vertical Slice\nBranch: ${BRANCH}\nAsset checkpoint: ${CHECKPOINT}\n\nCurrent cultivation: ${S.cultivationNumber}\nTree: ${TREE[S.treeStage-1]} / 6 · ${S.treeGrowth}%\nGarden: ${S.gardenHarmony}%\nCanopy: ${LABEL[S.canopyType]||S.canopyType} · stage ${S.canopyStage}\nBlossom: ${['None','Buds','Partial Bloom','Full Bloom'][S.blossomState]} · ${LABEL[S.blossomVariant]}\nPattern: ${LABEL[S.rakePattern]}\nMotif: ${LABEL[S.motif]}\nStones: ${LABEL[S.stoneLayout]}\nHarmony Seals: ${S.resources.harmonySeals}\nSave: ${saveState}`}
function render(){renderScene();renderPanel();renderStatus()}
function spend(cost){for(const [k,v] of Object.entries(cost))if(S.resources[k]<v){toast(`Not enough ${k.replace(/[A-Z]/g,m=>' '+m).toLowerCase()}.`);return false}for(const [k,v] of Object.entries(cost))S.resources[k]-=v;return true}
function progress(tree,garden){S.treeGrowth=clamp(S.treeGrowth+tree,0,100);S.gardenHarmony=clamp(S.gardenHarmony+garden,0,100);syncDerived();markDirty()}
function groveRecord(){return {id:`first-bloom-${S.cultivationNumber}`,cultivationNumber:S.cultivationNumber,completedAt:new Date().toISOString(),treeShape:S.treeShape,canopyType:S.canopyType,canopyStage:S.canopyStage,blossomState:S.blossomState,blossomVariant:S.blossomVariant,rakePattern:S.rakePattern,motif:S.motif,stoneLayout:S.stoneLayout,nameLayout:S.nameLayout,mossAccent:S.mossAccent,petalAccent:S.petalAccent}}
function addToGrove(){if(S.treeGrowth!==100||S.gardenHarmony!==100||!S.completed)return false;const id=`first-bloom-${S.cultivationNumber}`;if(S.grove.some(g=>g.id===id))return false;S.grove.push(groveRecord());return true}
function ceremony(){if(S.treeGrowth<100||S.gardenHarmony<100){toast('Tree Growth and Garden Harmony must both reach 100%.');return false}if(S.completionClaimed||alreadyRecorded()){toast('This cultivation already awarded its Harmony Seal.');return false}S.blossomState=3;S.canopyStage=4;S.petalAccent=true;S.treeFx=true;S.completed=true;S.completionClaimed=true;S.resources.harmonySeals+=1;addToGrove();markDirty();save();render();const el=$('ceremony');el.hidden=false;$('sanctuaryApp').classList.add('ceremony-active');clearTimeout(ceremonyTimer);ceremonyTimer=setTimeout(()=>{el.hidden=true;$('sanctuaryApp').classList.remove('ceremony-active');toast('First Bloom saved to the Grove. Harmony Seal +1.')},2300);return true}
function newCycle(){const keep={resources:S.resources,grove:S.grove,summonResults:S.summonResults,lastSummon:S.lastSummon,cultivationNumber:S.cultivationNumber+1};S=normalize({...defaults(),...keep});saveState='dirty';save('A fresh cultivation has begun.');render()}
function applyPreset(n){if(!DEV||![1,2,3,4,5,6].includes(n))return false;S.presetBackup=structuredClone({...S,presetBackup:null});if(S.completed||alreadyRecorded())S.cultivationNumber=Math.max(S.cultivationNumber,...S.grove.map(g=>Number(g.cultivationNumber)||0))+1;const base={completionClaimed:false,completed:false,treeFx:false,petalAccent:false,mossAccent:false};if(n===1)Object.assign(S,base,{treeGrowth:0,gardenHarmony:0,canopyStage:0,blossomState:0,rakePattern:'still_water',motif:'none',stoneLayout:'centered'});if(n===2)Object.assign(S,base,{treeGrowth:25,gardenHarmony:20,canopyStage:1,blossomState:0,rakePattern:'still_water',motif:'none',stoneLayout:'centered'});if(n===3)Object.assign(S,base,{treeGrowth:55,gardenHarmony:50,canopyStage:3,blossomState:0,rakePattern:'flowing_river',motif:'blazing_spiral',stoneLayout:'riverbank'});if(n===4)Object.assign(S,base,{treeGrowth:88,gardenHarmony:88,canopyStage:4,blossomState:2,rakePattern:'spiral_wind',motif:'petal_drift',stoneLayout:'mountain',mossAccent:true,petalAccent:true});if(n===5)Object.assign(S,base,{treeGrowth:100,gardenHarmony:100,canopyStage:4,blossomState:3,rakePattern:'ripple_ring',motif:'blazing_spiral',stoneLayout:'mountain',mossAccent:true,petalAccent:true,treeFx:true});if(n===6){Object.assign(S,{treeGrowth:100,gardenHarmony:100,canopyStage:4,blossomState:3,rakePattern:'spiral_wind',motif:'petal_drift',stoneLayout:'mountain',mossAccent:true,petalAccent:true,treeFx:true,completionClaimed:true,completed:true});addToGrove()}syncDerived();markDirty();save(`Preset ${n} loaded.`);render()}
function setTreeStage(n){n=clamp(n,1,6);S.treeGrowth=n===6?100:(n-1)*20;S.treeStage=n;S.rootState=ROOT_BY_STAGE[n-1];S.canopyStage=CANOPY_BY_STAGE[n-1];if(n<5)S.blossomState=0;markDirty();save();render()}
function mutate(action){
 if(action==='water'&&spend({spiritWater:1}))progress(12,0);else if(action==='nourish'&&spend({leafEssence:25}))progress(18,0);else if(action==='prune'&&spend({leafEssence:15,gardenStone:5})){progress(16,0);S.treeShape=cycle(SHAPES,S.treeShape)}else if(action==='rake'&&spend({gardenStone:10})){progress(0,14);S.rakePattern=cycle(RAKES,S.rakePattern)}else if(action==='stones'&&spend({gardenStone:20})){progress(0,12);S.stoneLayout=cycle(STONES,S.stoneLayout)}else if(action==='refine'&&spend({spiritWater:1,leafEssence:10}))progress(0,18);else if(action==='complete'){ceremony();return}else if(action==='new-cycle'){newCycle();return}else if(action==='summon'){if(!spend({harmonySeals:1}))return;const rewards=['Sacred Moss Sample','Moonlit Bonsai Pot','Jade Garden Charm','Spirit Water Vessel'];const result={reward:rewards[S.summonResults.length%rewards.length],at:new Date().toISOString()};S.lastSummon=result;S.summonResults.push(result);markDirty();save('One Harmony Seal consumed.')}else return;save();render()
}
function devControls(){const buttons=(items,cls='')=>`<div class="dev-group ${cls}">${items.map(([label,act,c=''])=>`<button type="button" data-dev="${act}" class="${c}">${label}</button>`).join('')}</div>`;$('devControls').innerHTML=`
 <details open><summary>TEST PRESETS</summary>${buttons([["PRESET 1 — NEW GARDEN","preset-1"],["PRESET 2 — EARLY GROWTH","preset-2"],["PRESET 3 — MID CULTIVATION","preset-3"],["PRESET 4 — NEAR BLOOM","preset-4"],["PRESET 5 — COMPLETION READY","preset-5"],["PRESET 6 — COMPLETED / GROVE TEST","preset-6"],["Restore pre-preset cultivation","undo-preset"]],'preset-grid')}</details>
 <details><summary>TREE</summary>${buttons([["← Previous stage","tree-prev"],["Next stage →","tree-next"],...[1,2,3,4,5,6].map(n=>[`Stage ${n}`,`tree-${n}`]),["Green canopy","canopy-green"],["Jade canopy","canopy-jade"],["Cycle canopy stage","canopy-stage"],["Cycle blossom stage","blossom-stage"],["Cycle blossom theme","blossom-theme"],["Toggle tree FX","tree-fx"]])}</details>
 <details><summary>GARDEN</summary>${buttons([["Harmony 0%","harmony-0"],["Harmony 25%","harmony-25"],["Harmony 50%","harmony-50"],["Harmony 75%","harmony-75"],["Harmony 100%","harmony-100"],["Cycle rake pattern","rake-cycle"],["Cycle motif","motif-cycle"],["Cycle stone layout","stone-cycle"],["Toggle moss accent","moss-toggle"],["Toggle petal accent","petal-toggle"],["Name: Straight","name-straight"],["Name: Arc","name-arc"],["Name: Seal","name-seal"]])}</details>
 <details><summary>RESOURCES</summary>${buttons([["+100 Leaf Essence","resource-leaf"],["+100 Garden Stone","resource-stone"],["+10 Spirit Water","resource-water"],["+1 Harmony Seal","resource-seal"],["Refill all DEV resources","resource-refill","wide"]])}</details>
 <details><summary>FLOW</summary>${buttons([["Fresh cultivation","flow-fresh"],["Mid-growth","flow-mid"],["Mature tree","flow-mature"],["Completion-ready","flow-ready"],["Trigger First Bloom ceremony","flow-complete","wide"],["Add completed tree to Grove","flow-grove","wide"],["Reset current cultivation","flow-reset","danger wide"],["Full Sanctuary reset","flow-full-reset","danger wide"]])}</details>
 <details><summary>PERSISTENCE</summary>${buttons([["Save state","save"],["Reload state","reload"],["Clear local save","clear-save","danger wide"]])}</details>`}
function devAction(a){if(!DEV)return;if(a==='undo-preset'){if(S.presetBackup){const backup=S.presetBackup;S=normalize({...backup,resources:S.resources,grove:S.grove,summonResults:S.summonResults,lastSummon:S.lastSummon,presetBackup:null});save();render()}return}if(a.startsWith('preset-'))return applyPreset(Number(a.at(-1)));if(a==='tree-prev')return setTreeStage(S.treeStage-1);if(a==='tree-next')return setTreeStage(S.treeStage+1);if(/^tree-\d$/.test(a))return setTreeStage(Number(a.at(-1)));if(a==='canopy-green')S.canopyType='green';if(a==='canopy-jade')S.canopyType='jade';if(a==='canopy-stage')S.canopyStage=(S.canopyStage+1)%5;if(a==='blossom-stage')S.blossomState=(S.blossomState+1)%4;if(a==='blossom-theme')S.blossomVariant=cycle(BLOSSOMS,S.blossomVariant);if(a==='tree-fx')S.treeFx=!S.treeFx;if(a.startsWith('harmony-'))S.gardenHarmony=Number(a.split('-')[1]);if(a==='rake-cycle')S.rakePattern=cycle(RAKES,S.rakePattern);if(a==='motif-cycle')S.motif=cycle(MOTIFS,S.motif);if(a==='stone-cycle')S.stoneLayout=cycle(STONES,S.stoneLayout);if(a==='moss-toggle')S.mossAccent=!S.mossAccent;if(a==='petal-toggle')S.petalAccent=!S.petalAccent;if(a.startsWith('name-'))S.nameLayout=a.slice(5);if(a==='resource-leaf')S.resources.leafEssence+=100;if(a==='resource-stone')S.resources.gardenStone+=100;if(a==='resource-water')S.resources.spiritWater+=10;if(a==='resource-seal')S.resources.harmonySeals+=1;if(a==='resource-refill')Object.assign(S.resources,{leafEssence:9999,gardenStone:9999,spiritWater:999,harmonySeals:Math.max(10,S.resources.harmonySeals)});if(a==='flow-fresh')return applyPreset(1);if(a==='flow-mid')return applyPreset(3);if(a==='flow-mature')return applyPreset(4);if(a==='flow-ready')return applyPreset(5);if(a==='flow-complete')return ceremony();if(a==='flow-grove')return ceremony();if(a==='flow-reset'){const keep={resources:S.resources,grove:S.grove,summonResults:S.summonResults,lastSummon:S.lastSummon,cultivationNumber:S.cultivationNumber};S=normalize({...defaults(),...keep})}if(a==='flow-full-reset'){if(!confirm('Full Sanctuary reset removes resources, current cultivation, Grove records, and test summons. Continue?'))return;S=defaults()}if(a==='save')return save('Sanctuary state saved.');if(a==='reload')return reload();if(a==='clear-save'){if(!confirm('Clear the namespaced Sanctuary local save?'))return;localStorage.removeItem(KEY);S=defaults();saveState='dirty';render();toast('Sanctuary local save cleared.');return}markDirty();save();render()}
function openDev(open){if(!DEV)return;$('devPanel').classList.toggle('open',open);$('devPanel').setAttribute('aria-hidden',String(!open));$('devBackdrop').hidden=!open;$('devOpen').setAttribute('aria-expanded',String(open));if(open)renderStatus()}
document.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action)mutate(action);const choice=event.target.closest('[data-choice]');if(choice){S[choice.dataset.choice]=choice.dataset.value;markDirty();save();render()}const t=event.target.closest('[data-tab]');if(t){tab=t.dataset.tab;renderPanel()}const d=event.target.closest('[data-dev]')?.dataset.dev;if(d)devAction(d)});
$('homeButton').onclick=()=>{location.href='index.html'};$('devOpen').onclick=()=>openDev(true);$('devClose').onclick=()=>openDev(false);$('devBackdrop').onclick=()=>openDev(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')openDev(false)});
document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{console.error('Sanctuary production asset failed to load:',img.getAttribute('src'));img.dataset.assetMissing='true'}));
$('devOpen').hidden=!DEV;if(DEV)devControls();render();save();
window.BlazingSanctuary=Object.freeze({KEY,SCHEMA,DEV,getState:()=>structuredClone(S),save,reload,applyPreset,complete:ceremony,newCycle,addToGrove,assets:{TREE,RAKES,MOTIFS,STONES,BLOSSOMS,NAME_LAYOUTS}});
})();
