(()=>{
'use strict';
const STYLE_ID='bb-home-polish-v3';
const copy=el=>String(el?.innerText||el?.textContent||'').replace(/\s+/g,' ').trim();
const visible=el=>{if(!el||el.hidden)return false;const s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&s.opacity!=='0';};
function score(el){const text=copy(el);let n=0;if(/SELECT\s+YOUR\s+PATH/i.test(text))n+=6;if(/\bINVENTORY\b/i.test(text))n+=2;if(/OWNED\s+FIGHTERS/i.test(text))n+=2;if(/\bLEVEL\b|BLAZING\s+ROAD/i.test(text))n+=1;if(/\bBOSS\b|PHANTOM\s+CASTLE/i.test(text))n+=1;if(/\bSUMMONS?\b/i.test(text))n+=1;return n;}
function findHome(){const candidates=[...new Set(document.querySelectorAll('.screen,section,main,[role="main"],body>div'))].filter(el=>el.id!=='bbInventory'&&el.id!=='bbUnitDetails'&&visible(el));return candidates.map(el=>({el,score:score(el)})).filter(x=>x.score>=8).sort((a,b)=>b.score-a.score||a.el.querySelectorAll('*').length-b.el.querySelectorAll('*').length)[0]?.el||null;}
function hideLegacyWallpaper(root){if(!root)return;const rr=root.getBoundingClientRect();for(const img of root.querySelectorAll('img')){const r=img.getBoundingClientRect(),s=getComputedStyle(img);if(r.width>=rr.width*.78&&r.height>=rr.height*.55&&(s.position==='absolute'||s.position==='fixed'))img.classList.add('bb-home-old-wallpaper');}}
function rankSemantic(candidates,interactive){let best=null,bestScore=-1e9;for(const el of candidates){const text=copy(el),r=el.getBoundingClientRect(),tag=el.tagName;let s=0;if(tag==='BUTTON'||tag==='A')s+=interactive?100:18;if(el.getAttribute('role')==='button')s+=interactive?85:12;if(typeof el.onclick==='function'||el.hasAttribute('onclick'))s+=interactive?48:4;try{if(getComputedStyle(el).cursor==='pointer')s+=interactive?30:3;}catch(_){}if(interactive&&r.width>=70&&r.height>=38)s+=20;if(!interactive&&/^H[1-4]$/.test(tag))s+=30;const descendants=el.querySelectorAll('*').length;s+=Math.max(0,12-Math.min(12,descendants));s-=Math.max(0,text.length-24)*.35;if(s>bestScore){bestScore=s;best=el;}}return best;}
function semanticNode(root,rx,{interactive=false}={}){const broad='button,a,[role="button"],h1,h2,h3,h4,div,section,span';if(interactive){const primary=[...root.querySelectorAll('button,a,[role="button"],[onclick]')].filter(visible).filter(el=>rx.test(copy(el)));if(primary.length)return rankSemantic(primary,true);}const candidates=[...root.querySelectorAll(broad)].filter(visible).filter(el=>rx.test(copy(el)));return rankSemantic(candidates,interactive);}
function interactiveLeaf(el,rx){if(!el)return null;if(el.matches?.('button,a,[role="button"],[onclick]'))return el;const ancestor=el.closest?.('button,a,[role="button"],[onclick]');if(ancestor&&visible(ancestor)&&(!rx||rx.test(copy(ancestor))))return ancestor;const nested=[...el.querySelectorAll?.('button,a,[role="button"],[onclick]')||[]].filter(visible).filter(node=>!rx||rx.test(copy(node)));return nested.length?rankSemantic(nested,true):el;}
function clearActionMarks(root,key,keep){for(const el of root.querySelectorAll(`[data-bb-home-action="${key}"],.bb-home-action--${key}`)){if(el===keep)continue;el.removeAttribute('data-bb-home-action');el.classList.remove('bb-home-action',`bb-home-action--${key}`,'bb-home-grid-shell');}}
function resolveAction(root,key,rx){const marked=root.querySelector(`[data-bb-home-action="${key}"]`);const candidate=interactiveLeaf(marked,rx)||interactiveLeaf(semanticNode(root,rx,{interactive:true}),rx);if(!candidate)return null;clearActionMarks(root,key,candidate);candidate.classList.remove('bb-home-grid-shell');candidate.classList.add('bb-home-action',`bb-home-action--${key}`);candidate.dataset.bbHomeAction=key;return candidate;}
function commonAncestor(nodes,root){if(nodes.length<2)return nodes[0]?.parentElement||null;let n=nodes[0]?.parentElement||null;while(n&&n!==root){if(nodes.every(x=>n.contains(x)))return n;n=n.parentElement;}return null;}
function exposeGridItems(actions,group){if(!group)return;for(const shell of group.querySelectorAll('.bb-home-grid-shell'))shell.classList.remove('bb-home-grid-shell');const actionSet=new Set(actions);for(const action of actions){action?.classList.remove('bb-home-grid-shell');let node=action?.parentElement;while(node&&node!==group){if(!actionSet.has(node))node.classList.add('bb-home-grid-shell');node=node.parentElement;}}for(const action of actions)action?.classList.remove('bb-home-grid-shell');}
function labelMode(el,key){if(!el)return;el.dataset.bbHomeAction=key;el.classList.add('bb-home-action',`bb-home-action--${key}`);if(el.dataset.bbModeLabeled==='1')return;el.dataset.bbModeLabeled='1';const legacy=[...el.childNodes];legacy.forEach(n=>{if(n.nodeType===Node.TEXT_NODE)n.nodeValue='';else if(n.nodeType===Node.ELEMENT_NODE)n.classList.add('bb-mode-legacy');});const eyebrow=document.createElement('span'),title=document.createElement('strong'),desc=document.createElement('span'),play=document.createElement('span');eyebrow.className='bb-mode-eyebrow';title.className='bb-mode-title';desc.className='bb-mode-desc';play.className='bb-mode-play';if(key==='road'){eyebrow.textContent='ENDURANCE MODE';title.textContent='BLAZING ROAD';desc.textContent='Stage 1 · First Route';}else{eyebrow.textContent='CHALLENGE MODE';title.textContent='PHANTOM CASTLE';desc.textContent='Boss 1 · First Trial';}play.textContent='ENTER';el.append(eyebrow,title,desc,play);}
function installStyle(){if(document.getElementById(STYLE_ID))return;for(const id of ['bb-home-polish-v1','bb-home-polish-v2'])document.getElementById(id)?.remove();const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`
.bb-home-theme{--bb-home-gold:#f3c969;--bb-home-cream:#fff3d3;min-height:100dvh!important;color:var(--bb-home-cream)!important;font-family:var(--bb-font-animeace,'AnimeAce2',system-ui,sans-serif)!important}
.bb-home-theme::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:linear-gradient(180deg,rgba(6,9,17,.2),rgba(8,11,20,.015) 29%,rgba(6,7,13,.5) 75%,rgba(4,5,10,.88))}
.bb-home-theme .bb-home-title{color:#fff8e5!important;font-size:clamp(36px,5vw,64px)!important;line-height:.92!important;text-align:center!important;letter-spacing:-.035em!important;text-shadow:0 3px 0 rgba(31,18,10,.7),0 9px 26px rgba(0,0,0,.5)!important}
.bb-home-theme .bb-home-kicker{color:#f8e8bd!important;font-size:clamp(10px,1.4vw,15px)!important;letter-spacing:.2em!important;text-transform:uppercase!important;text-align:center!important;text-shadow:0 2px 10px rgba(0,0,0,.45)!important}
.bb-home-theme .bb-home-actions{position:relative!important;z-index:2!important;display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;align-items:stretch!important;gap:clamp(9px,1.35vw,14px)!important;width:min(92vw,940px)!important;max-width:940px!important;margin:clamp(14px,2.2vh,24px) auto 0!important;padding:2px!important;box-sizing:border-box!important}
.bb-home-theme .bb-home-grid-shell{display:contents!important}
.bb-home-theme .bb-home-action{position:relative!important;inset:auto!important;margin:0!important;width:100%!important;max-width:none!important;min-width:0!important;align-self:stretch!important;justify-self:stretch!important;overflow:hidden!important;isolation:isolate!important;box-sizing:border-box!important;border:1px solid rgba(255,222,145,.62)!important;border-radius:18px 7px 18px 7px!important;background:linear-gradient(145deg,rgba(28,29,42,.93),rgba(10,12,22,.95))!important;color:#fff4d5!important;font-family:inherit!important;font-weight:900!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.13),0 9px 24px rgba(0,0,0,.32)!important;-webkit-backdrop-filter:blur(9px);backdrop-filter:blur(9px);transition:transform .16s ease,filter .16s ease,border-color .16s ease,box-shadow .16s ease!important;animation:bbHomeCardIn .42s cubic-bezier(.2,.72,.24,1) both!important}
.bb-home-theme .bb-home-action::before,.bb-home-theme .bb-home-action::after{content:"";position:absolute;pointer-events:none;z-index:0}
.bb-home-theme .bb-home-action::before{inset:0;background:linear-gradient(112deg,rgba(255,255,255,.08),transparent 29%,transparent 72%,rgba(255,222,145,.05));opacity:.75}
.bb-home-theme .bb-home-action::after{width:90px;height:180%;right:-44px;top:-40%;transform:rotate(18deg);background:linear-gradient(90deg,transparent,rgba(255,255,255,.065),transparent)}
.bb-home-theme .bb-home-action:hover,.bb-home-theme .bb-home-action:focus-visible{filter:brightness(1.08) saturate(1.05);border-color:rgba(255,231,164,.9)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.16),0 12px 29px rgba(0,0,0,.36)!important;outline:none!important;transform:translateY(-2px)!important}
.bb-home-theme .bb-home-action:focus-visible{outline:2px solid rgba(255,237,174,.86)!important;outline-offset:3px!important}
.bb-home-theme .bb-home-action:active{transform:translateY(0) scale(.982)!important}
.bb-mode-legacy{display:none!important}
.bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{grid-column:span 3!important;min-height:146px!important;padding:20px 18px 17px!important;text-align:left!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:flex-end!important;border-width:1px!important}
.bb-home-theme .bb-home-action--road{border-color:rgba(255,221,120,.96)!important;background:radial-gradient(circle at 16% 18%,rgba(255,200,87,.28),transparent 34%),linear-gradient(132deg,rgba(142,77,23,.96),rgba(63,37,21,.96) 50%,rgba(18,19,28,.97))!important}
.bb-home-theme .bb-home-action--castle{border-color:rgba(226,149,193,.9)!important;background:radial-gradient(circle at 83% 16%,rgba(186,105,181,.25),transparent 34%),linear-gradient(132deg,rgba(96,34,65,.97),rgba(51,27,48,.97) 50%,rgba(17,17,29,.98))!important}
.bb-home-theme .bb-home-action--road::before,.bb-home-theme .bb-home-action--castle::before{inset:auto -24px -46px auto;width:170px;height:170px;border:1px solid rgba(255,245,205,.16);border-radius:50%;box-shadow:0 0 0 18px rgba(255,245,205,.035),0 0 0 42px rgba(255,245,205,.02);background:radial-gradient(circle,rgba(255,244,194,.08),transparent 62%);opacity:1}
.bb-home-theme .bb-home-action--road::after,.bb-home-theme .bb-home-action--castle::after{width:160px;height:260%;right:-58px;top:-80%;transform:rotate(24deg);background:linear-gradient(90deg,transparent 18%,rgba(255,255,255,.09) 48%,transparent 78%);opacity:.62}
.bb-mode-eyebrow,.bb-mode-title,.bb-mode-desc,.bb-mode-play{position:relative!important;z-index:2!important}
.bb-mode-eyebrow{font:900 9px/1.1 system-ui,sans-serif!important;letter-spacing:.2em!important;color:#ffe8a6!important;text-shadow:0 2px 8px rgba(0,0,0,.5)!important}
.bb-home-action--castle .bb-mode-eyebrow{color:#ffd0e5!important}
.bb-mode-title{display:block!important;margin-top:7px!important;font-size:clamp(19px,2.45vw,29px)!important;line-height:.95!important;letter-spacing:-.025em!important;color:#fff9e9!important;text-shadow:0 2px 9px rgba(0,0,0,.45)!important;white-space:nowrap!important}
.bb-mode-desc{margin-top:9px!important;font:750 10px/1.2 system-ui,sans-serif!important;letter-spacing:.02em!important;color:rgba(255,244,218,.79)!important;text-shadow:0 2px 7px rgba(0,0,0,.42)!important}
.bb-mode-play{position:absolute!important;right:13px!important;top:12px!important;padding:6px 9px 6px 10px!important;border:1px solid rgba(255,239,183,.58)!important;border-radius:999px!important;background:rgba(9,9,13,.42)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08)!important;font:900 8px/1 system-ui,sans-serif!important;letter-spacing:.17em!important;color:#ffe69c!important}
.bb-mode-play::after{content:"›";padding-left:5px;font-size:11px;line-height:0}
.bb-home-theme .bb-home-action--summon,.bb-home-theme .bb-home-action--inventory,.bb-home-theme .bb-home-action--forge{grid-column:span 2!important;min-height:62px!important;padding:11px 10px!important;font-size:clamp(10px,1.35vw,14px)!important;letter-spacing:.035em!important}
.bb-home-theme .bb-home-actions > #summonsBtn.bb-home-action--summon,.bb-home-theme .bb-home-actions > #inventoryBtn.bb-home-action--inventory,.bb-home-theme .bb-home-actions > #forgeBtn.bb-home-action--forge{grid-area:auto!important;grid-column:auto/span 2!important;grid-row:auto!important;inline-size:auto!important;block-size:auto!important;width:auto!important;height:auto!important;min-width:0!important;max-width:none!important;max-height:none!important;aspect-ratio:auto!important;display:flex!important;flex:none!important;align-items:center!important;justify-content:center!important;place-self:stretch!important}
.bb-home-theme .bb-home-action--summon{animation-delay:.045s!important}.bb-home-theme .bb-home-action--inventory{animation-delay:.08s!important}.bb-home-theme .bb-home-action--forge{animation-delay:.115s!important}
.bb-home-theme .bb-home-action--road{animation-delay:0s!important}.bb-home-theme .bb-home-action--castle{animation-delay:.035s!important}
.bb-home-theme .bb-home-ambient{position:absolute!important;inset:0!important;z-index:0!important;overflow:hidden!important;pointer-events:none!important}
.bb-home-theme .bb-home-ambient i{position:absolute;width:10px;height:10px;border-radius:50%;opacity:.2;background:radial-gradient(circle,#fff8d8 0 16%,#f3c969 18% 36%,transparent 68%);animation:bbHomeDrift 8s ease-in-out infinite alternate}
.bb-home-theme .bb-home-ambient i:nth-child(1){left:10%;top:35%}.bb-home-theme .bb-home-ambient i:nth-child(2){right:12%;top:28%;animation-delay:-2.2s}.bb-home-theme .bb-home-ambient i:nth-child(3){left:72%;top:57%;animation-delay:-4.1s}
@keyframes bbHomeCardIn{from{opacity:0;transform:translateY(9px) scale(.992)}to{opacity:1;transform:translateY(0) scale(1)}}
@keyframes bbHomeDrift{from{transform:translateY(0);opacity:.08}to{transform:translateY(-18px);opacity:.28}}
@media(max-width:620px){
 .bb-home-theme .bb-home-actions{width:min(94vw,500px)!important;gap:9px!important;margin-top:clamp(10px,1.8vh,17px)!important}
 .bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{grid-column:1/-1!important;min-height:96px!important;padding:14px 13px 12px!important}
 .bb-mode-title{font-size:clamp(17px,5.1vw,22px)!important;margin-top:5px!important}
 .bb-mode-desc{font-size:9px!important;margin-top:6px!important;max-width:78%!important}
 .bb-mode-play{right:10px!important;top:9px!important;padding:5px 7px 5px 8px!important;font-size:7px!important}
 .bb-home-theme .bb-home-action--summon,.bb-home-theme .bb-home-action--inventory,.bb-home-theme .bb-home-action--forge{min-height:56px!important;padding:9px 6px!important;font-size:clamp(9px,2.55vw,11px)!important}
}
@media(max-width:390px){
 .bb-home-theme .bb-home-title{font-size:clamp(33px,10.5vw,44px)!important}
 .bb-home-theme .bb-home-kicker{font-size:9px!important;letter-spacing:.16em!important}
 .bb-home-theme .bb-home-actions{width:94vw!important;gap:7px!important}
 .bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{min-height:91px!important}
 .bb-home-theme .bb-home-action--summon,.bb-home-theme .bb-home-action--inventory,.bb-home-theme .bb-home-action--forge{min-height:54px!important;font-size:9px!important}
}
@media(max-height:620px) and (orientation:landscape){
 .bb-home-theme .bb-home-actions{margin-top:8px!important;gap:7px!important}
 .bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{min-height:90px!important;padding-top:12px!important;padding-bottom:10px!important}
 .bb-home-theme .bb-home-action--summon,.bb-home-theme .bb-home-action--inventory,.bb-home-theme .bb-home-action--forge{min-height:48px!important}
 .bb-mode-desc{margin-top:5px!important}
}
@media(prefers-reduced-motion:reduce){.bb-home-theme .bb-home-action,.bb-home-theme .bb-home-ambient i{animation:none!important;transition:none!important}}
`;document.head.appendChild(style);}
function decorate(root){const title=semanticNode(root,/^BLAZING\s+BATTLE$/i);if(title)title.classList.add('bb-home-title');const kicker=semanticNode(root,/^SELECT\s+YOUR\s+PATH$/i);if(kicker)kicker.classList.add('bb-home-kicker');for(const group of root.querySelectorAll('.bb-home-actions'))group.classList.remove('bb-home-actions');const roadRx=/^(?:LEVEL\s*1|(?:ENDURANCE\s+MODE\s+)?BLAZING\s+ROAD.*)$/i,castleRx=/^(?:BOSS\s*1|(?:CHALLENGE\s+MODE\s+)?PHANTOM\s+CASTLE.*)$/i;const road=resolveAction(root,'road',roadRx),castle=resolveAction(root,'castle',castleRx);labelMode(road,'road');labelMode(castle,'castle');const specs=[['summon',/^SUMMONS?\s*[✦★◆◇]?$/i],['inventory',/^INVENTORY\s*[✦★◆◇]?$/i],['forge',/^FORGE\s*[✦★◆◇]?$/i]],actions=[road,castle].filter(Boolean);for(const [key,rx] of specs){const el=resolveAction(root,key,rx);if(el)actions.push(el);}const uniqueActions=[...new Set(actions)];const group=commonAncestor(uniqueActions,root);if(group&&group!==root){group.classList.add('bb-home-actions');exposeGridItems(uniqueActions,group);}let ambient=root.querySelector(':scope > .bb-home-ambient');if(!ambient){ambient=document.createElement('div');ambient.className='bb-home-ambient';ambient.setAttribute('aria-hidden','true');ambient.innerHTML='<i></i><i></i><i></i>';root.prepend(ambient);}return uniqueActions.length;}
let homeRoot=null;function apply(){const found=findHome();if(found)homeRoot=found;const root=homeRoot&&document.body.contains(homeRoot)&&visible(homeRoot)?homeRoot:null;if(!root)return false;installStyle();root.classList.add('bb-home-theme');hideLegacyWallpaper(root);decorate(root);return true;}let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply();});}new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true});document.addEventListener('click',()=>setTimeout(apply,0),true);window.addEventListener('resize',schedule,{passive:true});setTimeout(apply,0);window.BlazingHomeSkin=Object.freeze({apply,findHome,decorate});
})();