(()=>{
'use strict';
const STYLE_ID='bb-home-polish-v2';
const copy=el=>String(el?.innerText||el?.textContent||'').replace(/\s+/g,' ').trim();
const visible=el=>{if(!el||el.hidden)return false;const s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&s.opacity!=='0';};
function score(el){const text=copy(el);let n=0;if(/SELECT\s+YOUR\s+PATH/i.test(text))n+=6;if(/\bINVENTORY\b/i.test(text))n+=2;if(/OWNED\s+FIGHTERS/i.test(text))n+=2;if(/\bLEVEL\b|BLAZING\s+ROAD/i.test(text))n+=1;if(/\bBOSS\b|PHANTOM\s+CASTLE/i.test(text))n+=1;if(/\bSUMMONS?\b/i.test(text))n+=1;return n;}
function findHome(){const candidates=[...new Set(document.querySelectorAll('.screen,section,main,[role="main"],body>div'))].filter(el=>el.id!=='bbInventory'&&el.id!=='bbUnitDetails'&&visible(el));return candidates.map(el=>({el,score:score(el)})).filter(x=>x.score>=8).sort((a,b)=>b.score-a.score||a.el.querySelectorAll('*').length-b.el.querySelectorAll('*').length)[0]?.el||null;}
function hideLegacyWallpaper(root){if(!root)return;const rr=root.getBoundingClientRect();for(const img of root.querySelectorAll('img')){const r=img.getBoundingClientRect(),s=getComputedStyle(img);if(r.width>=rr.width*.78&&r.height>=rr.height*.55&&(s.position==='absolute'||s.position==='fixed'))img.classList.add('bb-home-old-wallpaper');}}
function removeLeakedLegacyText(root){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const doomed=[];while(walker.nextNode()){const n=walker.currentNode,t=n.nodeValue||'';if(/bindLegacyTakeover|findInventoryReturn|legacyScreen|inventoryReturn/i.test(t)&&/[{};=]/.test(t))doomed.push(n);}doomed.forEach(n=>n.remove());}
function removeLiteralNewlineArtifacts(root=document.body){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const doomed=[];while(walker.nextNode()){const n=walker.currentNode,p=n.parentElement;if(p?.closest('script,style,pre,code,textarea'))continue;if(String(n.nodeValue||'').trim()==='\\n')doomed.push(n);}doomed.forEach(n=>n.remove());}
function semanticNode(root,rx,{interactive=false}={}){const candidates=[...root.querySelectorAll('button,a,[role="button"],h1,h2,h3,h4,div,section,span')].filter(visible).filter(el=>rx.test(copy(el)));let best=null,bestScore=-1e9;for(const el of candidates){const text=copy(el),r=el.getBoundingClientRect(),tag=el.tagName;let s=0;if(tag==='BUTTON'||tag==='A')s+=interactive?80:18;if(el.getAttribute('role')==='button')s+=interactive?65:12;if(typeof el.onclick==='function'||el.hasAttribute('onclick'))s+=interactive?35:4;try{if(getComputedStyle(el).cursor==='pointer')s+=interactive?24:3;}catch(_){}if(interactive&&r.width>=86&&r.height>=38)s+=18;if(!interactive&&/^H[1-4]$/.test(tag))s+=30;const descendants=el.querySelectorAll('*').length;s+=Math.max(0,12-Math.min(12,descendants));s-=Math.max(0,text.length-24)*.35;if(s>bestScore){bestScore=s;best=el;}}return best;}
function commonAncestor(nodes,root){if(nodes.length<2)return nodes[0]?.parentElement||null;let n=nodes[0]?.parentElement||null;while(n&&n!==root){if(nodes.every(x=>n.contains(x)))return n;n=n.parentElement;}return null;}
function labelMode(el,key){if(!el)return;el.dataset.bbHomeAction=key;el.classList.add('bb-home-action',`bb-home-action--${key}`);if(el.dataset.bbModeLabeled==='1')return;el.dataset.bbModeLabeled='1';el.textContent='';const eyebrow=document.createElement('span'),title=document.createElement('strong'),desc=document.createElement('span'),play=document.createElement('span');eyebrow.className='bb-mode-eyebrow';title.className='bb-mode-title';desc.className='bb-mode-desc';play.className='bb-mode-play';if(key==='road'){eyebrow.textContent='ENDURANCE MODE';title.textContent='BLAZING ROAD';desc.textContent='Stage 1 · Begin the Journey';play.textContent='ENTER';}else{eyebrow.textContent='CHALLENGE MODE';title.textContent='PHANTOM CASTLE';desc.textContent='Boss 1 · Face the Challenge';play.textContent='ENTER';}el.append(eyebrow,title,desc,play);}
function installStyle(){if(document.getElementById(STYLE_ID))return;document.getElementById('bb-home-polish-v1')?.remove();const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`
.bb-home-theme{--bb-home-gold:#f3c969;--bb-home-cream:#fff3d3;min-height:100dvh!important;color:var(--bb-home-cream)!important;font-family:var(--bb-font-animeace,'AnimeAce2',system-ui,sans-serif)!important}.bb-home-theme::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background:linear-gradient(180deg,rgba(6,9,17,.28) 0%,rgba(8,11,20,.03) 34%,rgba(8,9,16,.08) 55%,rgba(6,7,13,.62) 82%,rgba(4,5,10,.86) 100%)}
.bb-home-theme .bb-home-title{color:#fff8e5!important;font-size:clamp(34px,8.5vw,58px)!important;line-height:.96!important;letter-spacing:.025em!important;text-align:center!important;text-shadow:0 3px 0 rgba(31,18,10,.72),0 8px 22px rgba(0,0,0,.48),0 0 20px rgba(248,195,91,.22)!important}.bb-home-theme .bb-home-kicker{color:#f8e8bd!important;font-size:clamp(11px,3vw,16px)!important;letter-spacing:.16em!important;text-transform:uppercase!important;text-align:center!important;text-shadow:0 2px 8px rgba(0,0,0,.7)!important}
.bb-home-theme .bb-home-actions{position:relative!important;z-index:2!important;display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:clamp(8px,1.8vw,13px)!important;width:min(94vw,760px)!important;margin-inline:auto!important}.bb-home-theme .bb-home-action{position:relative!important;isolation:isolate!important;overflow:hidden!important;box-sizing:border-box!important;border:1px solid rgba(255,222,145,.7)!important;border-radius:17px 6px 17px 6px!important;background:linear-gradient(145deg,rgba(28,29,42,.92),rgba(10,12,22,.93))!important;color:#fff4d5!important;font-family:inherit!important;font-weight:900!important;letter-spacing:.045em!important;text-shadow:0 2px 8px rgba(0,0,0,.64)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.12),0 8px 20px rgba(0,0,0,.3)!important;backdrop-filter:blur(9px);transition:transform .13s ease,filter .13s ease,box-shadow .13s ease!important}.bb-home-theme .bb-home-action:hover,.bb-home-theme .bb-home-action:focus-visible{filter:brightness(1.1);outline:none!important}.bb-home-theme .bb-home-action:active{transform:scale(.975)!important}
.bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{grid-column:span 3!important;min-height:132px!important;padding:17px 16px 16px!important;text-align:left!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:flex-end!important}.bb-home-theme .bb-home-action--road{border-color:rgba(255,220,116,.96)!important;background:linear-gradient(140deg,rgba(132,74,24,.94),rgba(57,34,22,.94) 54%,rgba(15,17,26,.95))!important}.bb-home-theme .bb-home-action--castle{border-color:rgba(218,137,170,.9)!important;background:linear-gradient(140deg,rgba(95,31,54,.95),rgba(50,25,42,.95) 54%,rgba(14,15,25,.96))!important}.bb-mode-eyebrow{font:900 9px/1.1 system-ui,sans-serif!important;letter-spacing:.18em!important;color:#ffe8a6!important}.bb-home-action--castle .bb-mode-eyebrow{color:#ffc6dc!important}.bb-mode-title{display:block!important;margin-top:7px!important;font-size:clamp(17px,3.8vw,25px)!important;line-height:1!important;color:#fff9e9!important}.bb-mode-desc{margin-top:8px!important;font:700 10px/1.2 system-ui,sans-serif!important;color:rgba(255,244,218,.78)!important;text-shadow:none!important}.bb-mode-play{position:absolute!important;right:11px!important;top:10px!important;padding:5px 8px!important;border:1px solid rgba(255,239,183,.58)!important;border-radius:999px!important;background:rgba(12,10,13,.45)!important;font:900 8px/1 system-ui,sans-serif!important;letter-spacing:.15em!important;color:#ffe69c!important;text-shadow:none!important}.bb-home-action--castle .bb-mode-play{color:#ffd2e3!important}.bb-home-theme .bb-home-action--summon,.bb-home-theme .bb-home-action--inventory,.bb-home-theme .bb-home-action--forge{grid-column:span 2!important;min-height:58px!important;padding:10px 8px!important;font-size:clamp(10px,2.5vw,14px)!important}.bb-home-theme .bb-home-action--forge{border-color:rgba(193,145,255,.72)!important}
.bb-home-theme .bb-home-ambient{position:absolute!important;inset:0!important;z-index:0!important;overflow:hidden!important;pointer-events:none!important}.bb-home-theme .bb-home-ambient i{position:absolute;width:10px;height:10px;border-radius:50%;opacity:.22;background:radial-gradient(circle,#fff8d8 0 16%,#f3c969 18% 36%,rgba(243,201,105,0) 68%);animation:bbHomeDrift 8s ease-in-out infinite alternate}.bb-home-theme .bb-home-ambient i:nth-child(1){left:10%;top:35%}.bb-home-theme .bb-home-ambient i:nth-child(2){right:12%;top:28%}.bb-home-theme .bb-home-ambient i:nth-child(3){left:72%;top:57%}@keyframes bbHomeDrift{from{transform:translateY(0);opacity:.1}to{transform:translateY(-18px);opacity:.3}}@media(max-width:560px){.bb-home-theme .bb-home-actions{width:min(94vw,470px)!important;gap:8px!important}.bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{min-height:116px!important;padding:14px 11px 12px!important}.bb-mode-title{font-size:clamp(15px,4.7vw,21px)!important}.bb-mode-desc{font-size:9px!important;max-width:82%!important}.bb-home-theme .bb-home-action--summon,.bb-home-theme .bb-home-action--inventory,.bb-home-theme .bb-home-action--forge{min-height:54px!important;font-size:10px!important}}@media(max-width:370px){.bb-home-theme .bb-home-action--road,.bb-home-theme .bb-home-action--castle{grid-column:1/-1!important;min-height:92px!important}}@media(prefers-reduced-motion:reduce){.bb-home-theme .bb-home-action,.bb-home-theme .bb-home-ambient i{animation:none!important;transition:none!important}}
`;document.head.appendChild(style);}
function decorate(root){const title=semanticNode(root,/^BLAZING\s+BATTLE$/i);if(title)title.classList.add('bb-home-title');const kicker=semanticNode(root,/^SELECT\s+YOUR\s+PATH$/i);if(kicker)kicker.classList.add('bb-home-kicker');let road=root.querySelector('[data-bb-home-action="road"]')||semanticNode(root,/^LEVEL\s*1$/i,{interactive:true}),castle=root.querySelector('[data-bb-home-action="castle"]')||semanticNode(root,/^BOSS\s*1$/i,{interactive:true});labelMode(road,'road');labelMode(castle,'castle');const specs=[['summon',/^SUMMONS?\s*[✦★◆◇]?$/i],['inventory',/^INVENTORY\s*[✦★◆◇]?$/i],['forge',/^FORGE\s*[✦★◆◇]?$/i]],actions=[road,castle].filter(Boolean);for(const [key,rx] of specs){const el=semanticNode(root,rx,{interactive:true});if(!el)continue;el.classList.add('bb-home-action',`bb-home-action--${key}`);el.dataset.bbHomeAction=key;actions.push(el);}const group=commonAncestor(actions,root);if(group&&group!==root)group.classList.add('bb-home-actions');let ambient=root.querySelector(':scope > .bb-home-ambient');if(!ambient){ambient=document.createElement('div');ambient.className='bb-home-ambient';ambient.setAttribute('aria-hidden','true');ambient.innerHTML='<i></i><i></i><i></i>';root.prepend(ambient);}return actions.length;}
let homeRoot=null;function apply(){removeLiteralNewlineArtifacts(document.body);const found=findHome();if(found)homeRoot=found;const root=homeRoot&&document.body.contains(homeRoot)&&visible(homeRoot)?homeRoot:null;document.querySelectorAll('.bb-home-theme').forEach(el=>{if(el!==root)el.classList.remove('bb-home-theme');});if(!root)return false;installStyle();root.classList.add('bb-home-theme');hideLegacyWallpaper(root);removeLeakedLegacyText(root);decorate(root);return true;}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply();});}new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden','class','style']});document.addEventListener('click',()=>setTimeout(apply,0),true);document.addEventListener('pointerup',()=>setTimeout(apply,0),true);window.addEventListener('resize',schedule,{passive:true});setTimeout(apply,0);window.BlazingHomeSkin=Object.freeze({apply,findHome,decorate});
})();
